### ISSUE TITLE
Keeping env credentials of workflow files private using Github Secrets

### ISSUE THREAD

**Issue by abhiram11** [kunal-kushwaha/supabase-demo#3]
I think the SUPABASE_ACCESS_TOKEN (critical) and SUPABASE_DB_PASSWORD should be kept hidden from the workflow files and stored in Github Secrets.

They can be accessed in the workflow files using `SUPABASE_ACCESS_TOKEN : ${{secrets.SUPABASE_ACCESS_TOKEN}}` later.

**Comment by kunal-kushwaha** [comment]
Don't worry it's deleted from my account.
